var names = [
  "Az androidos srác",
  "Ákos",
  "Áron",
  "Balázs",
  "Bolgárkertészek",
  "Az ember",
  "Endre",
  "Freescale",
  "Ildi",
  "Ili",
  "Kálmán",
  "A Kálmán Bt.",
  "Kína",
  "Laci",
  "A Mentor",
  "A Micron",
  "Nem szimpatikus banda",
  "Tomi",
  "Az urak",
  "Zimbabwe",
  "Zotya",
];