// 0 : sima
// 1 : A sima
// 2 : tárgyeset
// 3 : A tárgyeset
// 4 : valvel
// 5 : A valvel
// 6 : naknek
// 7 : A naknek
// 8 : banben
// 9 : A banben
// 10 : tobbes
// 11 : A tobbes
// 12 : birtokos ( e/1 )
// 13 : A birtokos

var whiteCards = [
  ["120 mikroszekes taszkváltás", "a 120 mikroszekes taszkváltás",
    "120 mikroszekes taszkváltást", "a 120 mikroszekes taszkváltást",
    "120 mikroszekes taszkváltással", "a 120 mikroszekes taszkváltással",
    "120 mikroszekes taszkváltásnak", "a 120 mikroszekes taszkváltásnak",
    "120 mikroszekes taszkváltásban", "a 120 mikroszekes taszkváltásban",
    "120 mikroszekes taszkváltások", "a 120 mikroszekes taszkváltások",
    "120 mikroszekes taszkváltásom", "a 120 mikroszekes taszkváltásom"
  ],
  ["ablak", "az ablak",
    "ablakot", "az ablakot",
    "ablakkal", "az ablakkal",
    "ablaknak", "az ablaknak",
    "ablakban", "az ablakban",
    "ablakok", "az ablakok",
    "ablakom", "az ablakom",
  ],
  ["AES", "az AES",
    "AES-t", "az AES-t",
    "AES-sel", "az AES-sel",
    "AES-nek", "az AES-nek",
    "AES-ben", "az AES-ben",
    "AES-ek", "az AES-ek",
    "AES-em", "az AES-em",
  ],
  ["alap ASLR", "az alap ASLR",
    "alap ASLR-t", "az alap ASLR-t",
    "alap ASLR-rel", "az alap ASLR-rel",
    "alap ASLR-nek", "az alap ASLR-nek",
    "alap ASLR-ben", "az alap ASLR-ben",
    "alap ASLR-ek", "az alap ASLR-ek",
    "alap ASLR-em", "az alap ASLR-em",
  ],
  ["androidos srác", "az androidos srác",
    "androidos srácot", "az androidos srácot",
    "androidos sráccal", "az androidos sráccal",
    "androidos srácnak", "az androidos srácnak",
    "androidos srácban", "az androidos srácban",
    "androidos srácok", "az androidos srácok",
    "androidos srácom", "az androidos srácom",
  ],
  ["Ákos", "az Ákos",
    "Ákost", "az Ákost",
    "Ákossal", "az Ákossal",
    "Ákosnak", "az Ákosnak",
    "Ákosban", "az Ákosban",
    "Ákosok", "az Ákosok",
    "Ákosom", "az Ákosom",
  ],
  ["jól működő algoritmus", "a jól működő algoritmus",
    "jól működő algoritmust", "a jól működő algoritmust",
    "jól működő algoritmussal", "a jól működő algoritmussal",
    "jól működő algoritmusnak", "a jól működő algoritmusnak",
    "jól működő algoritmusban", "a jól működő algoritmusban",
    "jól működő algoritmusok", "a jól működő algoritmusok",
    "jól működő algoritmusom", "a jól működő algoritmusom",
  ],
  ["Áron", "az Áron",
    "Áront", "az Áront",
    "Áronnal", "az Áronnal",
    "Áronnak", "az Áronnak",
    "Áronban", "az Áronban",
    "Áronok", "az Áronok",
    "Áronom", "az Áronom",
  ],
  ["balfasz társaság", "a balfasz társaság",
    "balfasz társaságot", "a balfasz társaságot",
    "balfasz társasággal", "a balfasz társasággal",
    "balfasz társaságnak", "a balfasz társaságnak",
    "balfasz társaságban", "a balfasz társaságban",
    "balfasz társaságok", "a balfasz társaságok",
    "balfasz társaságom", "a balfasz társaságom",
  ],
  ["Balázs", "a Balázs",
    "Balázst", "a Balázst",
    "Balázzsal", "a Balázzsal",
    "Balázsnak", "a Balázsnak",
    "Balázsban", "a Balázsban",
    "Balázsok", "a Balázsok",
    "Balázsom", "a Balázsom",
  ],
  ["bolgárkertész", "a bolgárkertész",
    "bolgárkertészt", "a bolgárkertészt",
    "bolgárkertésszel", "a bolgárkertésszel",
    "bolgárkertésznek", "a bolgárkertésznek",
    "bolgárkertészben", "a bolgárkertészben",
    "bolgárkertészek", "a bolgárkertészek",
    "bolgárkertészem", "a bolgárkertészem",
  ],
  ["Bombay-tál", "a Bombay-tál",
    "Bombay-tálat", "a Bombay-tálat",
    "Bombay-tállal", "a Bombay-tállal",
    "Bombay-tálnak", "a Bombay-tálnak",
    "Bombay-tálban", "a Bombay-tálban",
    "Bombay-tálak", "a Bombay-tálak",
    "Bombay-tálam", "a Bombay-tálam",
  ],
  ["buddy allocator", "a buddy allocator",
    "buddy allocatort", "a buddy allocatort",
    "buddy allocatorral", "a buddy allocatorral",
    "buddy allocatornak", "a buddy allocatornak",
    "buddy allocatorban", "a buddy allocatorban",
    "buddy allocatorok", "a buddy allocatorok",
    "buddy allocatorom", "a buddy allocatorom",
  ],
  ["C", "a C",
    "C-t", "a C-t",
    "C-vel", "a C-vel",
    "C-nek", "a C-nek",
    "C-ben", "a C-ben",
    "C-k", "a C-k",
    "C-m", "a C-m",
  ],
  ["C-sín", "a C-sín",
    "C-sínt", "a C-sínt",
    "C-sínnel", "a C-sínnel",
    "C-sínnek", "a C-sínnek",
    "C-sínben", "a C-sínben",
    "C-sínek", "a C-sínek",
    "C-sínem", "a C-sínem",
  ],
  ["cache", "a cache",
    "cache-t", "a cache-t",
    "cache-sel", "a cache-sel",
    "cache-nek", "a cache-nek",
    "cache-ben", "a cache-ben",
    "cache-ek", "a cache-ek",
    "cache-em", "a cache-em",
  ],
  ["CAN-chat", "a CAN-chat",
    "CAN-chat-et", "a CAN-chat-et",
    "CAN-chat-tel", "a CAN-chat-tel",
    "CAN-chat-nek", "a CAN-chat-nek",
    "CAN-chat-ben", "a CAN-chat-ben",
    "CAN-chat-ek", "a CAN-chat-ek",
    "CAN-chat-em", "a CAN-chat-em",
  ],
  ["checkout", "a checkout",
    "checkout-ot", "a checkout-ot",
    "checkout-tal", "a checkout-tal",
    "checkout-nak", "a checkout-nak", ,
    "checkout-ban", "a checkout-ban",
    "checkout-ok", "a checkout-ok",
    "checkout-om", "a checkout-om",
  ],
  ["clean-up", "a clean-up",
    "clean-up-ot", "a clean-up-ot",
    "clean-up-pal", "a clean-up-pal",
    "clean-up-nak", "a clean-up-nak",
    "clean-up-ban", "a clean-up-ban",
    "clean-up-ok", "a clean-up-ok",
    "clean-up-om", "a clean-up-om",
  ],
  ["CRT0", "a CRT0",
    "CRT0-t", "a CRT0-t",
    "CRT0-val", "a CRT0-val",
    "CRT0-nak", "a CRT0-nak",
    "CRT0-ban", "a CRT0-ban",
    "CRT0-k", "a CRT0-k",
    "CRT0-m", "a CRT0-m",
  ],
  ["csapat", "a csapat",
    "csapatot", "a csapatot",
    "csapattal", "a csapattal",
    "csapatnak", "a csapatnak",
    "csapatban", "a csapatban",
    "csapatok", "a csapatok",
    "csapatom", "a csapatom",
  ],
  ["datasheet", "a datasheet",
    "datasheet-et", "a datasheet-et",
    "datasheet-tel", "a datasheet-tel",
    "datasheet-nek", "a datasheet-nek",
    "datasheet-ben", "a datasheet-ben",
    "datasheet-ek", "a datasheet-ek",
    "datasheet-em", "a datasheet-em",
  ],
  ["debug", "a debug",
    "debug-ot", "a debug-ot",
    "debug-gal", "a debug-gal",
    "debug-nak", "a debug-nak",
    "debug-ban", "a debug-ban",
    "debug-ok", "a debug-ok",
    "debug-om", "a debug-om",
  ],
  ["DIN-sín", "a DIN-sín",
    "DIN-sínt", "a DIN-sínt",
    "DIN-sínnel", "a DIN-sínnel",
    "DIN-sínnek", "a DIN-sínnek",
    "DIN-sínben", "a DIN-sínben",
    "DIN-sínek", "a DIN-sínek",
    "DIN-sínem", "a DIN-sínem",
  ],
  ["display", "a display",
    "display-t", "a display-t",
    "display-el", "a display-el",
    "display-nek", "a display-nek",
    "display-ben", "a display-ben",
    "display-ek", "a display-ek",
    "display-em", "a display-em",
  ],
  ["diszk", "a diszk",
    "diszket", "a diszket",
    "diszkkel", "a diszkkel",
    "diszknek", "a diszknek",
    "diszkben", "a diszkben",
    "diszkek", "a diszkek",
    "diszkem", "a diszkem",
  ],
  ["dokumentáció", "a dokumentáció",
    "dokumentációt", "a dokumentációt",
    "dokumentációval", "a dokumentációval",
    "dokumentációnak", "a dokumentációnak",
    "dokumentációban", "a dokumentációban",
    "dokumentációk", "a dokumentációk",
    "dokumentációm", "a dokumentációm",
  ],
  ["Emacs", "az Emacs",
    "Emacs-et", "az Emacs-et",
    "Emacs-szel", "az Emacs-szel",
    "Emacs-nek", "az Emacs-nek",
    "Emacs-ben", "az Emacs-ben",
    "Emacs-ek", "az Emacs-ek",
    "Emacs-em", "az Emacs-em",
  ],
  ["ember", "az ember",
    "embert", "az embert",
    "emberrel", "az emberrel",
    "embernek", "az embernek",
    "emberben", "az emberben",
    "emberek", "az emberek",
    "emberem", "az emberem",
  ],
  ["Endre", "az Endre",
    "Endrét", "az Endrét",
    "Endrével", "az Endrével",
    "Endrének", "az Endrének",
    "Endrében", "az Endrében",
    "Endrék", "az Endrék",
    "Endrém", "az Endrém",
  ],
  [
    "érdekes feladat", "az érdekes feladat",
    "érdekes feladatot", "az érdekes feladatot",
    "érdekes feladattal", "az érdekes feladattal",
    "érdekes feladatnak", "az érdekes feladatnak",
    "érdekes feladatban", "az érdekes feladatban",
    "érdekes feladatok", "az érdekes feladatok",
    "érdekes feladatom", "az érdekes feladatom",
  ],
  [
    "fali terminal", "a fali terminal",
    "fali terminalt", "a fali terminalt",
    "fali terminallal", "a fali terminallal",
    "fali terminalnak", "a fali terminalnak",
    "fali terminalban", "a fali terminalban",
    "fali terminalok", "a fali terminalok",
    "fali terminalom", "a fali terminalom",
  ],
  [
    "footprint", "a footprint",
    "footprintet", "a footprintet",
    "footprinttel", "a footprinttel",
    "footprintnek", "a footprintnek",
    "footprintben", "a footprintben",
    "footprintek", "a footprintek",
    "footprintem", "a footprintem",
  ],
  [
    "főzelékfaló", "a főzelékfaló",
    "főzelékfalót", "a főzelékfalót",
    "főzelékfalóval", "a főzelékfalóval",
    "főzelékfalónak", "a főzelékfalónak",
    "főzelékfalóban", "a főzelékfalóban",
    "főzelékfalók", "a főzelékfalók",
    "főzelékfalóm", "a főzelékfalóm",
  ],
  [
    "Freescale", "a Freescale",
    "Freescale-t", "a Freescale-t",
    "Freescale-lel", "a Freescale-lel",
    "Freescale-nek", "a Freescale-nek",
    "Freescale-ben", "a Freescale-ben",
    "Freescale-ek", "a Freescale-ek",
    "Freescale-em", "a Freescale-em",
  ],
  [
    "galambszarral és -tetemmel teli helyiség", "a galambszarral és -tetemmel teli helyiség",
    "galambszarral és -tetemmel teli helyiséget", "a galambszarral és -tetemmel teli helyiséget",
    "galambszarral és -tetemmel teli helyiséggel", "a galambszarral és -tetemmel teli helyiséggel",
    "galambszarral és -tetemmel teli helyiségnek", "a galambszarral és -tetemmel teli helyiségnek",
    "galambszarral és -tetemmel teli helyiségben", "a galambszarral és -tetemmel teli helyiségben",
    "galambszarral és -tetemmel teli helyiségek", "a galambszarral és -tetemmel teli helyiségek",
    "galambszarral és -tetemmel teli helyiségem", "a galambszarral és -tetemmel teli helyiségem",
  ],
  [
    "gateway", "a gateway",
    "gateway-t", "a gateway-t",
    "gateway-el", "a gateway-el",
    "gateway-nek", "a gateway-nek",
    "gateway-ben", "a gateway-ben",
    "gateway-ek", "a gateway-ek",
    "gateway-em", "a gateway-em",
  ],
  [
    "gyümölcs", "a gyümölcs",
    "gyümölcsöt", "a gyümölcsöt",
    "gyümölccsel", "a gyümölccsel",
    "gyümölcsnek", "a gyümölcsnek",
    "gyümölcsben", "a gyümölcsben",
    "gyümölcsök", "a gyümölcsök",
    "gyümölcsöm", "a gyümölcsöm",
  ],
  [
    "gw001", "a gw001",
    "gw001-et", "a gw001-et",
    "gw001-el", "a gw001-el",
    "gw001-nek", "a gw001-nek",
    "gw001-ben", "a gw001-ben",
    "gw001-ek", "a gw001-ek",
    "gw001-em", "a gw001-em",
  ],
  [
    "hadititok", "a hadititok",
    "hadititkot", "a hadititkot",
    "hadititokkal", "a hadititokkal",
    "hadititoknak", "a hadititoknak",
    "hadititokban", "a hadititokban",
    "hadititkok", "a hadititkok",
    "hadititkom", "a hadititkom",
  ],
  [
    "hát-hát-hát", "a hát-hát-hát",
    "hát-hát-hát-ot", "a hát-hát-hát-ot",
    "hát-hát-hát-tal", "a hát-hát-hát-tal",
    "hát-hát-hát-nak", "a hát-hát-hát-nak",
    "hát-hát-hát-ban", "a hát-hát-hát-ban",
    "hát-hát-hát-ok", "a hát-hát-hát-ok",
    "hát-hát-hát-om", "a hát-hát-hát-om",
  ],
  [
    "haver", "a haver",
    "havert", "a havert",
    "haverral", "a haverral",
    "havernak", "a havernak",
    "haverban", "a haverban",
    "haverok", "a haverok",
    "haverom", "a haverom",
  ],
  [
    "hegyirabló", "a hegyirabló",
    "hegyirablót", "a hegyirablót",
    "hegyirablóval", "a hegyirablóval",
    "hegyirablónak", "a hegyirablónak",
    "hegyirablóban", "a hegyirablóban",
    "hegyirablók", "a hegyirablók",
    "hegyirablóm", "a hegyirablóm",
  ],
  [
    "hely", "a hely",
    "helyet", "a helyet",
    "hellyel", "a hellyel",
    "helynek", "a helynek",
    "helyben", "a helyben",
    "helyek", "a helyek",
    "helyem", "a helyem",
  ],
  [
    "hibajavító kódolás RF kommunikációhoz mikorkontrolleren", "a hibajavító kódolás RF kommunikációhoz mikorkontrolleren",
    "hibajavító kódolást RF kommunikációhoz mikorkontrolleren", "a hibajavító kódolást RF kommunikációhoz mikorkontrolleren",
    "hibajavító kódolással RF kommunikációhoz mikorkontrolleren", "a hibajavító kódolással RF kommunikációhoz mikorkontrolleren",
    "hibajavító kódolásnak RF kommunikációhoz mikorkontrolleren", "a hibajavító kódolásnak RF kommunikációhoz mikorkontrolleren",
    "hibajavító kódolásban RF kommunikációhoz mikorkontrolleren", "a hibajavító kódolásban RF kommunikációhoz mikorkontrolleren",
    "hibajavító kódolások RF kommunikációhoz mikorkontrolleren", "a hibajavító kódolások RF kommunikációhoz mikorkontrolleren",
    "hibajavító kódolásom RF kommunikációhoz mikorkontrolleren", "a hibajavító kódolásom RF kommunikációhoz mikorkontrolleren",
  ],
  [
    "hülyeség", "a hülyeség",
    "hülyeséget", "a hülyeséget",
    "hülyeséggel", "a hülyeséggel",
    "hülyeségnek", "a hülyeségnek",
    "hülyeségben", "a hülyeségben",
    "hülyeségek", "a hülyeségek",
    "hülyeségem", "a hülyeségem",
  ],
  [
    "Ildi", "az Ildi",
    "Ildit", "az Ildit",
    "Ildivel", "az Ildivel",
    "Ildinek", "az Ildinek",
    "Ildiben", "az Ildiben",
    "Ildik", "az Ildik",
    "Ildim", "az Ildim",
  ],
  [
    "Ili", "az Ili",
    "Ilit", "az Ilit",
    "Ilivel", "az Ilivel",
    "Ilinek", "az Ilinek",
    "Iliben", "az Iliben",
    "Ilik", "az Ilik",
    "Ilim", "az Ilim",
  ],
  [
    "jójójójójó", "a jójójójójó",
    "jójójójójó-t", "a jójójójójó-t",
    "jójójójójó-val", "a jójójójójó-val",
    "jójójójójó-nak", "a jójójójójó-nak",
    "jójójójójó-ban", "a jójójójójó-ban",
    "jójójójójó-k", "a jójójójójó-k",
    "jójójójójó-m", "a jójójójójó-m",
  ],
  [
    "kalapsín", "a kalapsín",
    "kalapsínt", "a kalapsínt",
    "kalapsínnel", "a kalapsínnel",
    "kalapsínnek", "a kalapsínnek",
    "kalapsínben", "a kalapsínben",
    "kalapsínek", "a kalapsínek",
    "kalapsínem", "a kalapsínem",
  ],
  [
    "Kálmán", "a Kálmán",
    "Kálmánt", "a Kálmánt",
    "Kálmánnal", "a Kálmánnal",
    "Kálmánnak", "a Kálmánnak",
    "Kálmánban", "a Kálmánban",
    "Kálmánok", "a Kálmánok",
    "Kálmánom", "a Kálmánom",
  ],
  [
    "Kálmán Bt.", "a Kálmán Bt.",
    "Kálmán Bt.-t", "a Kálmán Bt.-t",
    "Kálmán Bt.-vel", "a Kálmán Bt.-vel",
    "Kálmán Bt.-nek", "a Kálmán Bt.-nek",
    "Kálmán Bt.-ben", "a Kálmán Bt.-ben",
    "Kálmán Bt.-k", "a Kálmán Bt.-k",
    "Kálmán Bt.-m", "a Kálmán Bt.-m",
  ],
  [
    "Kína", "a Kína",
    "Kínát", "a Kínát",
    "Kínával", "a Kínával",
    "Kínának", "a Kínának",
    "Kínában", "a Kínában",
    "Kínák", "a Kínák",
    "Kínám", "a Kínám",
  ],
  [
    "kódkonvenciók szerinti kódolás", "a kódkonvenciók szerinti kódolás",
    "kódkonvenciók szerinti kódolást", "a kódkonvenciók szerinti kódolást",
    "kódkonvenciók szerinti kódolással", "a kódkonvenciók szerinti kódolással",
    "kódkonvenciók szerinti kódolásnak", "a kódkonvenciók szerinti kódolásnak",
    "kódkonvenciók szerinti kódolásban", "a kódkonvenciók szerinti kódolásban",
    "kódkonvenciók szerinti kódolások", "a kódkonvenciók szerinti kódolások",
    "kódkonvenciók szerinti kódolásom", "a kódkonvenciók szerinti kódolásom",
  ],
  [
    "komoly fejlesztőmunka", "a komoly fejlesztőmunka",
    "komoly fejlesztőmunkát", "a komoly fejlesztőmunkát",
    "komoly fejlesztőmunkával", "a komoly fejlesztőmunkával",
    "komoly fejlesztőmunkának", "a komoly fejlesztőmunkának",
    "komoly fejlesztőmunkában", "a komoly fejlesztőmunkában",
    "komoly fejlesztőmunkák", "a komoly fejlesztőmunkák",
    "komoly fejlesztőmunkám", "a komoly fejlesztőmunkám",
  ],
  [
    "kernál", "a kernál",
    "kernált", "a kernált",
    "kernállal", "a kernállal",
    "kernálnak", "a kernálnak",
    "kernálban", "a kernálban",
    "kernálok", "a kernálok",
    "kernálom", "a kernálom",
  ],
  [
    "Laci", "a Laci",
    "Lacit", "a Lacit",
    "Lacival", "a Lacival",
    "Lacinak", "a Lacinak",
    "Laciban", "a Laciban",
    "Lacik", "a Lacik",
    "Lacim", "a Lacim",
  ],
  [
    "lelkük", "a lelkük",
    "lelküket", "a lelküket",
    "lelkükkel", "a lelkükkel",
    "lelküknek", "a lelküknek",
    "lelkükben", "a lelkükben",
    "lelkük", "a lelkük",
    "lelkem", "a lelkem",
  ],
  [
    "Linux", "a Linux",
    "Linux-ot", "a Linux-ot",
    "Linux-szal", "a Linux-szal",
    "Linux-nak", "a Linux-nak",
    "Linux-ban", "a Linux-ban",
    "Linux-ok", "a Linux-ok",
    "Linux-om", "a Linux-om",
  ],
  [
    "lottó ötös", "a lottó ötös",
    "lottó ötöst", "a lottó ötöst",
    "lottó ötössel", "a lottó ötössel",
    "lottó ötösnek", "a lottó ötösnek",
    "lottó ötösben", "a lottó ötösben",
    "lottó ötösök", "a lottó ötösök",
    "lottó ötösöm", "a lottó ötösöm",
  ],
  [
    "Makefile", "a Makefile",
    "Makefile-t", "a Makefile-t",
    "Makefile-lal", "a Makefile-lal",
    "Makefile-nak", "a Makefile-nak",
    "Makefile-ban", "a Makefile-ban",
    "Makefile-ok", "a Makefile-ok",
    "Makefile-om", "a Makefile-om",
  ],
  [
    "marketing szöveg", "a marketing szöveg",
    "marketing szöveget", "a marketing szöveget",
    "marketing szöveggel", "a marketing szöveggel",
    "marketing szövegnek", "a marketing szövegnek",
    "marketing szövegben", "a marketing szövegben",
    "marketing szövegek", "a marketing szövegek",
    "marketing szövegem", "a marketing szövegem",
  ],
  [
    "Mentor", "a Mentor",
    "Mentort", "a Mentort",
    "Mentorral", "a Mentorral",
    "Mentornak", "a Mentornak",
    "Mentorban", "a Mentorban",
    "Mentorok", "a Mentorok",
    "Mentorom", "a Mentorom",
  ],
  [
    "Micron", "a Micron",
    "Micront", "a Micront",
    "Micronnal", "a Micronnal",
    "Micronnak", "a Micronnak",
    "Micronban", "a Micronban",
    "Micronok", "a Micronok",
    "Micronom", "a Micronom",
  ],
  [
    "munkanélküliség", "a munkanélküliség",
    "munkanélküliséget", "a munkanélküliséget",
    "munkanélküliséggel", "a munkanélküliséggel",
    "munkanélküliségnek", "a munkanélküliségnek",
    "munkanélküliségben", "a munkanélküliségben",
    "munkanélküliségek", "a munkanélküliségek",
    "munkanélküliségem", "a munkanélküliségem",
  ],
  [
    "nem szimpatikus banda", "a nem szimpatikus banda",
    "nem szimpatikus bandát", "a nem szimpatikus bandát",
    "nem szimpatikus bandéval", "a nem szimpatikus bandéval",
    "nem szimpatikus bandának", "a nem szimpatikus bandának",
    "nem szimpatikus bandában", "a nem szimpatikus bandában",
    "nem szimpatikus bandák", "a nem szimpatikus bandák",
    "nem szimpatikus bandám", "a nem szimpatikus bandám",
  ],
  [
    "ngw001", "a ngw001",
    "ngw001-t", "a ngw001-t",
    "ngw001-el", "a ngw001-el",
    "ngw001-nek", "a ngw001-nek",
    "ngw001-ben", "a ngw001-ben",
    "ngw001-ek", "a ngw001-ek",
    "ngw001-em", "a ngw001-em",
  ],
  [
    "NYÁK", "a NYÁK",
    "NYÁK-ot", "a NYÁK-ot",
    "NYÁK-kal", "a NYÁK-kal",
    "NYÁK-nak", "a NYÁK-nak",
    "NYÁK-ban", "a NYÁK-ban",
    "NYÁK-ok", "a NYÁK-ok",
    "NYÁK-om", "a NYÁK-om",
  ],
  [
    "NYÁK-terv", "a NYÁK-terv",
    "NYÁK-tervet", "a NYÁK-tervet",
    "NYÁK-tervvel", "a NYÁK-tervvel",
    "NYÁK-tervnek", "a NYÁK-tervnek",
    "NYÁK-tervben", "a NYÁK-tervben",
    "NYÁK-tervek", "a NYÁK-tervek",
    "NYÁK-tervem", "a NYÁK-tervem",
  ],
  [
    "objektum orientált gondolkodás", "az objektum orientált gondolkodás",
    "objektum orientált gondolkodást", "az objektum orientált gondolkodást",
    "objektum orientált gondolkodással", "az objektum orientált gondolkodással",
    "objektum orientált gondolkodásnak", "az objektum orientált gondolkodásnak",
    "objektum orientált gondolkodásban", "az objektum orientált gondolkodásban",
    "objektum orientált gondolkodások", "az objektum orientált gondolkodások",
    "objektum orientált gondolkodásom", "az objektum orientált gondolkodásom",
  ],
  [
    "papír-ceruza", "a papír-ceruza",
    "papírt-ceruzát", "a papírt-ceruzát",
    "papíral-ceruzával", "a papíral-ceruzával",
    "papírnak-ceruzának", "a papírnak-ceruzának",
    "papírban-ceruzában", "a papírban-ceruzában",
    "papírok-ceruzák", "a papírok-ceruzák",
    "papírom-ceruzám", "a papírom-ceruzám",
  ],
  [
    "parfümillatú gyümölcs", "a parfümillatú gyümölcs",
    "parfümillatú gyümölcsöt", "a parfümillatú gyümölcsöt",
    "parfümillatú gyümölccsel", "a parfümillatú gyümölccsel",
    "parfümillatú gyümölcsnek", "a parfümillatú gyümölcsnek",
    "parfümillatú gyümölcsben", "a parfümillatú gyümölcsben",
    "parfümillatú gyümölcsök", "a parfümillatú gyümölcsök",
    "parfümillatú gyümölcsöm", "a parfümillatú gyümölcsöm",
  ],
  [
    "répa", "a répa",
    "répát", "a répát",
    "répával", "a répával",
    "répának", "a répának",
    "répában", "a répában",
    "répák", "a répák",
    "répám", "a répám",
  ],
  [
    "saját fejlesztésű multitasking preemptive operációs rendszer", "a saját fejlesztésű multitasking preemptive operációs rendszer",
    "saját fejlesztésű multitasking preemptive operációs rendszert", "a saját fejlesztésű multitasking preemptive operációs rendszert",
    "saját fejlesztésű multitasking preemptive operációs rendszerrel", "a saját fejlesztésű multitasking preemptive operációs rendszerrel",
    "saját fejlesztésű multitasking preemptive operációs rendszernek", "a saját fejlesztésű multitasking preemptive operációs rendszernek",
    "saját fejlesztésű multitasking preemptive operációs rendszerben", "a saját fejlesztésű multitasking preemptive operációs rendszerben",
    "saját fejlesztésű multitasking preemptive operációs rendszerek", "a saját fejlesztésű multitasking preemptive operációs rendszerek",
    "saját fejlesztésű multitasking preemptive operációs rendszerem", "a saját fejlesztésű multitasking preemptive operációs rendszerem",
  ],
  [
    "schematic", "a schematic",
    "schematic-ot", "a schematic-ot",
    "schematic-kal", "a schematic-kal",
    "schematic-nak", "a schematic-nak",
    "schematic-ban", "a schematic-ban",
    "schematic-ok", "a schematic-ok",
    "schematic-om", "a schematic-om",
  ],
  [
    "seed szerver", "a seed szerver",
    "seed szerver-t", "a seed szerver-t",
    "seed szerver-rel", "a seed szerver-rel",
    "seed szerver-nek", "a seed szerver-nek",
    "seed szerver-ben", "a seed szerver-ben",
    "seed szerver-ek", "a seed szerver-ek",
    "seed szerver-em", "a seed szerver-em",
  ],
  [
    "ST", "az ST",
    "ST-t", "az ST-t",
    "ST-vel", "az ST-vel",
    "ST-nek", "az ST-nek",
    "ST-ben", "az ST-ben",
    "ST-k", "az ST-k",
    "ST-m", "az ST-m",
  ],
  [
    "szar", "a szar",
    "szart", "a szart",
    "szarral", "a szarral",
    "szarnak", "a szarnak",
    "szarban", "a szarban",
    "szarok", "a szarok",
    "szarom", "a szarom",
  ],
  [
    "szemét", "a szemét",
    "szemetet", "a szemetet",
    "szeméttel", "a szeméttel",
    "szemétnek", "a szemétnek",
    "szemétben", "a szemétben",
    "szemetek", "a szemetek",
    "szemetem", "a szemetem",
  ],
  [
    "szék", "a szék",
    "széket", "a széket",
    "székkel", "a székkel",
    "széknek", "a széknek",
    "székben", "a székben",
    "székek", "a székek",
    "székem", "a székem",
  ],
  [
    "só", "a só",
    "sót", "a sót",
    "sóval", "a sóval",
    "sónak", "a sónak",
    "sóban", "a sóban",
    "sók", "a sók",
    "sóm", "a sóm",
  ],
  [
    "tolás", "a tolás",
    "tolást", "a tolást",
    "tolással", "a tolással",
    "tolásnak", "a tolásnak",
    "tolásban", "a tolásban",
    "tolások", "a tolások",
    "tolásom", "a tolásom",
  ],
  [
    "Tomi", "a Tomi",
    "Tomit", "a Tomit",
    "Tomival", "a Tomival",
    "Tominak", "a Tominak",
    "Tomiban", "a Tomiban",
    "Tomik", "a Tomik",
    "Tomim", "a Tomim",
  ],
  [
    "toroskáposzta", "a toroskáposzta",
    "toroskáposztát", "a toroskáposztát",
    "toroskáposztával", "a toroskáposztával",
    "toroskáposztának", "a toroskáposztának",
    "toroskáposztában", "a toroskáposztában",
    "toroskáposzták", "a toroskáposzták",
    "toroskáposztám", "a toroskáposztám",
  ],
  [
    "törő", "a törő",
    "törőt", "a törőt",
    "törővel", "a törővel",
    "törőnek", "a törőnek",
    "törőben", "a törőben",
    "törők", "a törők",
    "törőm", "a törőm",
  ],
  [
    "újrafelhasználható kód", "az újrafelhasználható kód",
    "újrafelhasználható kódot", "az újrafelhasználható kódot",
    "újrafelhasználható kóddal", "az újrafelhasználható kóddal",
    "újrafelhasználható kódnak", "az újrafelhasználható kódnak",
    "újrafelhasználható kódban", "az újrafelhasználható kódban",
    "újrafelhasználható kódok", "az újrafelhasználható kódok",
    "újrafelhasználható kódom", "az újrafelhasználható kódom",
  ],
  [
    "úr", "az úr",
    "urat", "az urat",
    "úrral", "az úrral",
    "úrnak", "az úrnak",
    "úrban", "az úrban",
    "urak", "az urak",
    "uram", "az uram",
  ],
  [
    "user interface", "a user interface",
    "user interface-t", "a user interface-t",
    "user interface-szel", "a user interface-szel",
    "user interface-nek", "a user interface-nek",
    "user interface-ben", "a user interface-ben",
    "user interface-ek", "a user interface-ek",
    "user interface-em", "a user interface-em",
  ],
  [
    "vastagtésztás pizza", "a vastagtésztás pizza",
    "vastagtésztás pizzát", "a vastagtésztás pizzát",
    "vastagtésztás pizzával", "a vastagtésztás pizzával",
    "vastagtésztás pizzának", "a vastagtésztás pizzának",
    "vastagtésztás pizzában", "a vastagtésztás pizzában",
    "vastagtésztás pizzák", "a vastagtésztás pizzák",
    "vastagtésztás pizzám", "a vastagtésztás pizzám",
  ],
  [
    "vékonytésztás pizza", "a vékonytésztás pizza",
    "vékonytésztás pizzát", "a vékonytésztás pizzát",
    "vékonytésztás pizzával", "a vékonytésztás pizzával",
    "vékonytésztás pizzának", "a vékonytésztás pizzának",
    "vékonytésztás pizzában", "a vékonytésztás pizzában",
    "vékonytésztás pizzák", "a vékonytésztás pizzák",
    "vékonytésztás pizzám", "a vékonytésztás pizzám",
  ],
  [
    "x86-64", "az x86-64",
    "x86-64-et", "az x86-64-et",
    "x86-64-gyel", "az x86-64-gyel",
    "x86-64-nek", "az x86-64-nek",
    "x86-64-ben", "az x86-64-ben",
    "x86-64-ek", "az x86-64-ek",
    "x86-64-em", "az x86-64-em",
  ],
  [
    "Zimbabwe", "a Zimbabwe",
    "Zimbabwét", "a Zimbabwét",
    "Zimbabwével", "a Zimbabwével",
    "Zimbabwének", "a Zimbabwének",
    "Zimbabwében", "a Zimbabwében",
    "Zimbabwék", "a Zimbabwék",
    "Zimbabwém", "a Zimbabwém",
  ],
  [
    "ZOC", "a ZOC",
    "ZOC-ot", "a ZOC-ot",
    "ZOC-cal", "a ZOC-cal",
    "ZOC-nak", "a ZOC-nak",
    "ZOC-ban", "a ZOC-ban",
    "ZOC-ok", "a ZOC-ok",
    "ZOC-om", "a ZOC-om",
  ],
  [
    "Zotya", "a Zotya",
    "Zotyát", "a Zotyát",
    "Zotyával", "a Zotyával",
    "Zotyának", "a Zotyának",
    "Zotyában", "a Zotyában",
    "Zotyák", "a Zotyák",
    "Zotyám", "a Zotyám",
  ],
  [
    "ZOTYAAAAAAAAA", "a ZOTYAAAAAAAAA",
    "ZOTYÁÁÁÁÁÁÁÁÁT", "a ZOTYÁÁÁÁÁÁÁÁÁT",
    "ZOTYÁÁÁÁÁÁÁÁÁVAL", "a ZOTYÁÁÁÁÁÁÁÁÁVAL",
    "ZOTYÁÁÁÁÁÁÁÁÁNAK", "a ZOTYÁÁÁÁÁÁÁÁÁNAK",
    "ZOTYÁÁÁÁÁÁÁÁÁBAN", "a ZOTYÁÁÁÁÁÁÁÁÁBAN",
    "ZOTYÁÁÁÁÁÁÁÁÁK", "a ZOTYÁÁÁÁÁÁÁÁÁK",
    "ZOTYÁÁÁÁÁÁÁÁÁM", "a ZOTYÁÁÁÁÁÁÁÁÁM",
  ],
]